### ISSUE TITLE
TODO-s

### ISSUE THREAD

**Issue by szepeviktor** [pedro-mendonca/GP-Project-Icon#8]
List of ideas:

- [x] Gallery image select, using the media uploader on frontend
- [x] Delete icon meta on deleting project
- [ ] Set allowed image types (png, jpg, gif, svg)
- [?] Clone icon meta on cloning project
- [ ] Check behavior on viewing a project which image was deleted from media library
- [ ] Dashicon (dashicon-slug)
- [-] Fontawesome (slug)
- [ ] Remove project icons meta on plugin uninstall

Resources:

https://derekspringer.wordpress.com/2015/05/07/using-the-wordpress-media-loader-in-the-front-end/
https://gist.github.com/bcole808/b31ed5101b1723e77dce
https://jeroensormani.com/how-to-include-the-wordpress-media-selector-in-your-plugin/
